// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBstMtmZ5IwIxgDR8QuBudbgWIVIwBDG4k',
    appId: '1:285789685618:web:a5558c3fd145179590ffeb',
    messagingSenderId: '285789685618',
    projectId: 'test01-611cd',
    authDomain: 'test01-611cd.firebaseapp.com',
    storageBucket: 'test01-611cd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj2F-F4mACfQVo7ktBp8cVlY2WbnhhuTU',
    appId: '1:285789685618:android:61e35fb9a343a2f890ffeb',
    messagingSenderId: '285789685618',
    projectId: 'test01-611cd',
    storageBucket: 'test01-611cd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_tSoBqXs-8QROLMiQ8wizDS2kpyeGgtg',
    appId: '1:285789685618:ios:d28656bccb7d6e2790ffeb',
    messagingSenderId: '285789685618',
    projectId: 'test01-611cd',
    storageBucket: 'test01-611cd.appspot.com',
    iosClientId: '285789685618-tp7pc90kj2mlq29cavdhs01qij3uc60l.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_tSoBqXs-8QROLMiQ8wizDS2kpyeGgtg',
    appId: '1:285789685618:ios:a398d3dea60d002190ffeb',
    messagingSenderId: '285789685618',
    projectId: 'test01-611cd',
    storageBucket: 'test01-611cd.appspot.com',
    iosClientId: '285789685618-77c14c7k2tilt1vioqlo3lkhrv8rll3p.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
